[default]
SMTPPASS='Suq97716'

[development]
DBPASS='postgres'
GQLPASS='Ciber$2022'
SSHPASS='Admin1234!'
REDSYS_KEY='sq7HjrUOBfKmC576ILgskD5srU870gJ7'

[production]
DBPASS='postgres'
GQLPASS='Ciber$2022'
SSHPASS='Admin1234!'
REDSYS_KEY='sq7HjrUOBfKmC576ILgskD5srU870gJ7'