[default]
API_PREFIX='/api/v1'
DBUSER='postgres'
DATABASE='niledb'
GQLUSER='modelsadmin'
SSHUSER='themes'

SMTPHOST='smtp.office365.com'
SMTPPORT='587'
SMTPFROM='no-reply@cotown.com'
SMTPUSER='no-reply@cotown.com'

BILLDATE='2023-06-01'
CHECKINDAYS=14

[development]
SERVER='experis.flows.ninja'
REDSYS_TERMINAL='002'
REDSYS_MERCHANTCODE='348032921'
REDSYS_MERCHANTURL='https://dev.cotown.ciber.es/api/v1/notify'

[production]
SERVER='core.cotown.com'
REDSYS_TERMINAL='002'
REDSYS_MERCHANTCODE='348032921'
REDSYS_MERCHANTURL='https://back.core.cotown/api/v1/notify'