[development]

DBPASS='postgres'
GQLPASS='Ciber$2022'
SSHPKEY='id_partner.pem'
SMTPPASS='Suq97716'
COOKIE_KEY='fno1EWVJ5m1b15ZzDVd3'
AC_KEY='b7c07c266ebc3fa5b5b55f9d17c702387b7130b2edd8194e3e9d3900c62cbbe9b3b27859'

# TPVs
REDSYS_KEY_DEFAULT='sq7HjrUOBfKmC576ILgskD5srU870gJ7'
REDSYS_KEY_COTOWN='sq7HjrUOBfKmC576ILgskD5srU870gJ7'
REDSYS_KEY_VANDOR='sq7HjrUOBfKmC576ILgskD5srU870gJ7'

[production]

DBPASS='postgres'
GQLPASS='Ciber$2022'
SSHPKEY='id_partner.pem'
SMTPPASS='Suq97716'
COOKIE_KEY='mcmjA9p6vFDE8UjuFyKp'
AC_KEY='b7c07c266ebc3fa5b5b55f9d17c702387b7130b2edd8194e3e9d3900c62cbbe9b3b27859'

# TPVs
REDSYS_KEY_DEFAULT='pAy69tUCrncRb9Q7pXk+4cIzvNrEspR1'
REDSYS_KEY_COTOWN='8HAa+9Qh3CuogttHEUGlO+MgJRFZHHNA'
REDSYS_KEY_VANDOR='apg+v+gklLxhPYQ7ZvhpqsV5GvgGUr4V'

# Vandor
43bdcc93-a03c-486f-894c-cd7377fdc459='0:9999'

# Lemos
d17da385-7167-47d0-af39-9732f4392595='5:5'