[development]

DBPASS='postgres'
GQLPASS='Ciber$2022'
SSHPKEY='id_partner.pem'
SMTPPASS='Suq97716'
COOKIE_KEY='fno1EWVJ5m1b15ZzDVd3'
REDSYS_KEY='sq7HjrUOBfKmC576ILgskD5srU870gJ7'
AC_KEY='b7c07c266ebc3fa5b5b55f9d17c702387b7130b2edd8194e3e9d3900c62cbbe9b3b27859'

[production]

DBPASS='postgres'
GQLPASS='Ciber$2022'
SSHPKEY='id_partner.pem'
SMTPPASS='Suq97716'
COOKIE_KEY='mcmjA9p6vFDE8UjuFyKp'
REDSYS_KEY='pAy69tUCrncRb9Q7pXk+4cIzvNrEspR1'
AC_KEY='b7c07c266ebc3fa5b5b55f9d17c702387b7130b2edd8194e3e9d3900c62cbbe9b3b27859'