[default]

# General
API_PREFIX='/api/v1'
DBUSER='postgres'
DATABASE='niledb'
GQLUSER='modelsadmin'
CUSTOMER='cotowngroup.com/customer'
EMAIL_TO='book@cotown.com'
AC_URL='https://vanguard-student-housing.api-us1.com/api/3/'

# Log level: CRITICAL=50, ERROR=40, WARNING=30, INFO=20, DEBUG=10
LOGLEVEL=10

# Email send
SMTPHOST='smtp.office365.com'
SMTPPORT='587'
SMTPFROM='Cotown <no-reply@cotown.com>'
SMTPUSER='no-reply@cotown.com'

# App parameters
BILLDATE='2023-11-01'
CONTRACTDATE='2023-11-06'
CHECKINDAYS=14
CHECKOUTDAYS=30

[development]

# Servers
SSHUSER='partner'
BACK='dev.cotown.ciber.es'
SERVER='experis.flows.ninja'

# Redsys
REDSYS_MERCHANTURL='https://dev.cotown.ciber.es/api/v1/notify'
REDSYS_URL='https://sis-t.redsys.es:25443/sis/realizarPago'

# TPVs
REDSYS_TERMINAL_DEFAULT='002'
REDSYS_MERCHANTCODE_DEFAULE='348032921'

REDSYS_TERMINAL_COTOWN='002'
REDSYS_MERCHANTCODE_COTOWN='348032921'

REDSYS_TERMINAL_VANDOR='002'
REDSYS_MERCHANTCODE_VANDOR='348032921'

# Email send
SMTPSEND=0

[production]

# Servers
SSHUSER='partner'
BACK='back.cotown.com'
SERVER='core.cotown.com'

# Redsys
REDSYS_MERCHANTURL='https://back.cotown.com/api/v1/notify'
REDSYS_URL='https://sis.redsys.es/sis/realizarPago'

# TPVs
REDSYS_TERMINAL_DEFAULT='002'
REDSYS_MERCHANTCODE_DEFAULT='348032921'

REDSYS_TERMINAL_COTOWN='002'
REDSYS_MERCHANTCODE_COTOWN='348032921'

REDSYS_TERMINAL_VANDOR='002'
REDSYS_MERCHANTCODE_VANDOR='348032921'

# Email send
SMTPSEND=1