server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: cotowndev
  static_configs:
  - targets:
      - localhost
    labels:
      container: backdev
      host: mv-cotown-core-dev
      job: varlogs
      __path__: /var/log/dev/*.log
- job_name: cotownpre
  static_configs:
  - targets:
      - localhost
    labels:
      container: backpre
      host: mv-cotown-core-dev
      job: varlogs
      __path__: /var/log/pre/*.log
