[default]

# Log level: CRITICAL=50, ERROR=40, WARNING=30, INFO=20, DEBUG=10
LOGLEVEL=10

# Core
GQLUSER='modelsadmin'

# Origin DB
DBHOST='core.cotown.com'
DBUSER='postgres'
DBNAME='niledb'
SSHUSER='partner'

# Destination DB
DWDBHOST='localhost'
DWDBUSER='cotown'
DWDBNAME='dw'

# SAP URLs
SAPUSER = 'lorumdesarrollo'
SAPURL_GL='https://my429724.businessbydesign.cloud.sap/sap/byd/odata/ana_businessanalytics_analytics.svc/RPFINGLAU02_Q0001QueryResults'